version: '3'
services:
  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: always
  jguweka:
    image: aymmenn/jguweka:OAS3
    restart: always
    links:
      - "mongo:mongodb"
    ports:
      - "8081-8099:8080"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
