version: '3'
services:
  mongo:
    image: mongo
    restart: always
  jguweka:
    image: aymmenn/jguweka:OAS3
    restart: always
    links:
      - "mongo:mongodb"
    expose:
      - "8080"
      - "8849"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
  proxy:
    image: dockercloud/haproxy
    links:
      - jguweka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"


